### ISSUE TITLE
TDialog  tDialog = new TDialog.Builder(getChildFragmentManager())....show(); 这样写就报错啊

### ISSUE THREAD

**Issue by richfuns** [Timmy-zzh/TDialog#19]
`
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Dialog.requestWindowFeature(int)' on a null object reference
        at com.timmy.tdialog.base.BaseDialogFragment.onViewCreated(BaseDialogFragment.java:92)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:6295)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
`

只要赋值给一个全局的Tdialog对象，就报这个空指针异常，麻烦作者看一下，谢谢

**Comment by Timmy-zzh** [comment]
你好,麻烦描述一下使用场景

**Comment by richfuns** [comment]
@Timmy-zzh 直接new 使用没问题，但是如果赋值给一个对象，比如TDialog tDialog =new TDialog.Builder(getChildFragmentManager())....show();   这样就会报这个错误

**Comment by Timmy-zzh** [comment]
getChildFragmentManager()使用的不是同一个Fragment管理器
