### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by studyandroid** [Timmy-zzh/TDialog#23]
Caused by: java.lang.IllegalStateException:Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
at tdialog.base.BaseDialogFragment.show(Native Method)
at tdialog.TDialog.show(Native Method)

**Comment by Timmy-zzh** [comment]
你好,你是在什么时候调用的show方法?

**Comment by studyandroid** [comment]
@Override public void show(FragmentManager manager, String tag) {
        //super.show(manager, tag);
        FragmentTransaction ft = manager.beginTransaction();
        ft.add(this, tag);
        /*ft.commit();*/
        // 这里吧原来的commit()方法换成了commitAllowingStateLoss()
        ft.commitAllowingStateLoss();
    }
这个是修改过的不会出现崩溃了

**Comment by Timmy-zzh** [comment]
ok,知道问题出在哪里

**Comment by Bertkiing** [comment]
please quikly....

**Comment by Timmy-zzh** [comment]
2.0已处理该问题

**Comment by zwping** [comment]
tDialog.dismissAllowingStateLoss();
这个你没有加上去

**Comment by HoCham-Lu** [comment]
ft.commitAllowingStateLoss();  也会出现崩溃   try 一下吧

**Comment by Timmy-zzh** [comment]
已处理，请使用最新版本
