### ISSUE TITLE
 IllegalStateException

### ISSUE THREAD

**Issue by HoCham-Lu** [Timmy-zzh/TDialog#28]
能更新一下吗？  在sho() 时候 try 一下

**Comment by Timmy-zzh** [comment]
麻烦提供一下完整报错日志，我需要找到问题根源，try不能解决问题的

**Comment by ChamLu** [comment]
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:637)
        at android.support.v4.app.DialogFragment.show(DialogFragment.java:144)
